name: Entry Edit
description: Request for edits to a single existing topic, concept, or term entry.
title: "[Edit] Subject: Entry Name"
labels: ["enhancement", "typo"]
assignees: "Name here"
body:
  - type: dropdown
    id: edits
    attributes:
      label: Type of Edit (select all that apply)
      multiple: true
      options:
        - Fix grammar, spelling, formatting
        - Clarify unclear content and/or terms
        - Add new content (definitions, codeblocks, etc.)
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Description (optional)
      description: "Additional context behind edits."
      placeholder: "Please provide any additional context/reasoning behind the edits here."
  - type: markdown
    attributes:
      value: |
        In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md), we recommend checking out the following before submtting a PR:
        - [Entry templates](https://github.com/Codecademy/docs/blob/main/documentation/)
        - [Content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)
        - [Markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
  - type: checkboxes
    id: maintainers
    attributes:
      label: For Maintainers
      options:
        - label: Labels added
          required: false
        - label: Issue is assigned
          required: false
